default:
  image: node:18-alpine3.17
  interruptible: false

variables:
  DOCKER_IMAGE: fayvori/react-gitlabcicd

stages:
  - test 
  - deploy 

cache:
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - npm i --silent
  script:
    - CI=true npm test
  tags:
    - netlify 
    - shared

deploy:
  stage: deploy
  only:
    - main
  before_script:
    - npm i --silent
    - npm run build
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir build 
  tags:
    - netlify
    - shared
  when: manual
